const itemActionTypes = {
  FETCH_FOOD_ITEMS_START: 'FETCH_FOOD_ITEMS_START',
  FETCH_FOOD_ITEMS_SUCCESS: 'FETCH_FOOD_ITEMS_SUCCESS',
  FETCH_FOOD_ITEMS_FAILURE: 'FETCH_FOOD_ITEMS_FAILURE'
}

export default itemActionTypes